#!/bin/bash
echo "load venv"
source venv/bin/activate

python3 main.py -debug 0 -stage 10
Of="$(date +%Y%m%d)_$(date +%T)_TVAC_TRANSITION2.zip"
zip -r $Of ./servicedata/output
rm -R ./servicedata/output
