#!/bin/bash
echo "load venv"
source venv/bin/activate

python3 main.py -debug 0 -stage 12
Of="$(date +%Y%m%d)_$(date +%T)_TVAC_TRANSITION4.zip"
zip -r $Of ./servicedata/output
rm -R ./servicedata/output
